version: "3.8"

services:

  configserver:
    image: hendersonporfirio/configserver-bank:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
      - tuyobank

  accounts:
    image: hendersonporfirio/accountsconfigserver:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - tuyobank
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  loans:
    image: hendersonporfirio/loansconfigserver:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - tuyobank
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  cards:
    image: hendersonporfirio/cardsconfigserver:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - tuyobank
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

networks:
  tuyobank: